# Generated by Django 4.2.1 on 2023-06-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameMate7', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Proveedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
