# Generated by Django 4.2.1 on 2023-05-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameMate7', '0001_initial'),
    ]

    operations = [
    ]
