# Generated by Django 4.2.1 on 2023-05-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameMate7', '0002_auto_20230521_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'datos de inicio de Sesion',
                'verbose_name_plural': 'Logins',
                'db_table': 'Login',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('nombre_usuario', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=25)),
                ('contraseña', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'datos de registrados',
                'verbose_name_plural': 'Registros',
                'db_table': 'Registro',
            },
        ),
    ]
