# Generated by Django 4.2.1 on 2023-05-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameMate7', '0003_login_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='nickname',
            new_name='user',
        ),
    ]
